### ISSUE TITLE
NEW ROM REQUEST

### ISSUE THREAD

**Issue by marzhall** [metasyn/learn-uxn#1]
Please add my rom!

See here: https://github.com/marzhall/dvd_screen

Very important to have a screensaver for your machine. And what better than the best screensaver of all?

![this guy!](https://raw.githubusercontent.com/marzhall/dvd_screen/main/dvd_example.gif)

Let me know if you'd like any changes. It's my first program of note, so any feedback would actually be super helpful. Thanks!

**Comment by metasyn** [comment]
Hi @marzhall !

The first submission!!! :tada: 

It's been added :) I copied over the `.tal` from your repo and put it in a new folder called submissions. Feel free to make a PR to the contents as well if you want to tweak it or be added as a contributor to the project. I took the liberty of adding a line to the `.tal` file with a link to your username / repo.

Best,
Xander
